const String getReviews = """query getReviews(\$inventoryId:String){
  getReviews(inventoryId:\$inventoryId){
   averageRating,
   canReview,
    reviews{
      id,
      rating,
      text,
      images,
      customer{
        name
      }
    },
    error{
      path
      message
    }
  }
}""";
